steps:
  - id: build image
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=$_IMAGE_NAME:$_REVISION_SUFFIX
      - --destination=$_IMAGE_NAME:$_IMAGE_TAG
      - --cache=true
    # secretEnv:
    #   - COMPOSER_AUTH

  - id: deploy image
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --region=$_REGION
      - --image=$_IMAGE_NAME:$_REVISION_SUFFIX
      - --min-instances=0
      - --no-traffic
      - --revision-suffix=$_REVISION_SUFFIX
      - --tag=$_TRAFFIC_TAG

  - id: add commit status
    name: europe-docker.pkg.dev/$PROJECT_ID/build/github-status-updater
    entrypoint: github-status-updater
    env:
      - GITHUB_ACTION=update_state
      - GITHUB_STATE=success
      - GITHUB_OWNER=$_PR_PREVIEW_REPO_OWNER
      - GITHUB_REPO=$_PR_PREVIEW_REPO_NAME
      - GITHUB_REF=$COMMIT_SHA
      - GITHUB_CONTEXT=$_PR_PREVIEW_CONTEXT
      - GITHUB_DESCRIPTION=$_PR_PREVIEW_DESCRIPTION
      - GITHUB_TARGET_URL=$_SERVICE_URL
    secretEnv:
      - GITHUB_TOKEN

substitutions:
  _REGION: europe-north1
  _REVISION_SUFFIX: ${SHORT_SHA}-${BUILD_ID:0:8}
  _REVISION_NAME: ${_SERVICE_NAME}-${_REVISION_SUFFIX}
  _ARTIFACT_REGISTRY_NAME: run
  _IMAGE_NAME: europe-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_NAME}/${_SERVICE_NAME}
  _IMAGE_TAG: pr-${_PR_NUMBER}
  _TRAFFIC_TAG: pr-${_PR_NUMBER}
  _SERVICE_URL: https://${_TRAFFIC_TAG}.${_SERVICE_NAME}.${_SERVICE_URL_SUFFIX}

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/PR_PREVIEW_STATUS_GITHUB_TOKEN/versions/latest
      env: GITHUB_TOKEN
    # - versionName: projects/${PROJECT_ID}/secrets/COMPOSER_AUTH/versions/latest
    #   env: COMPOSER_AUTH

options:
  logging: CLOUD_LOGGING_ONLY
#   machineType: E2_HIGHCPU_8

timeout: 900s
