steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --target=${_BUILD_TARGET}
      - --destination=$_IMAGE_NAME:$_REVISION_SUFFIX
      - --destination=$_IMAGE_NAME:$_IMAGE_TAG
      - --cache=true
      - --cache-ttl=24h
    # secretEnv:
    #   - COMPOSER_AUTH

  - id: deploy image
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --region=$_REGION
      - --image=$_IMAGE_NAME:$_REVISION_SUFFIX
      - --min-instances=$_MIN_INSTANCES
      - --no-traffic
      - --revision-suffix=$_REVISION_SUFFIX

  - id: update traffic
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - update-traffic
      - $_SERVICE_NAME
      - --region=$_REGION
      - --to-revisions=$_REVISION_NAME=100
      - --async

substitutions:
  _REGION: europe-north1
  _REVISION_SUFFIX: ${SHORT_SHA}-${BUILD_ID:0:8}
  _REVISION_NAME: ${_SERVICE_NAME}-${_REVISION_SUFFIX}
  _ARTIFACT_REGISTRY_NAME: run
  _IMAGE_NAME: europe-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_NAME}/${_SERVICE_NAME}
  _IMAGE_TAG: latest
  _MIN_INSTANCES: "1"

# availableSecrets:
#   secretManager:
#     - versionName: projects/${PROJECT_ID}/secrets/COMPOSER_AUTH/versions/latest
#       env: COMPOSER_AUTH

# options:
#   machineType: E2_HIGHCPU_8

timeout: 900s
